# Notes:
# - Minimal appveyor.yml file is an empty file. All sections are optional.
# - Indent each level of configuration with 2 spaces. Do not use tabs!
# - All section names are case-sensitive.
# - Section names should be unique on each level.

#---------------------------------#
#  general configuration          #
#---------------------------------#

# version format
version: '{branch}-{build}'

# Do not build on tags (GitHub only)
skip_tags: true

# avoid malicious attempt via pull requests
branches:
  only:
    - master


#---------------------------------#
#  environment configuration      #
#---------------------------------#

# environment variables
# build system info: http://www.appveyor.com/docs/installed-software
os: Visual Studio 2015

environment:
  REPO_DIR: &REPO_DIR c:\project  # directory created by appveyor

  NASM_URL: http://www.nasm.us/pub/nasm/releasebuilds/2.12.01/win32/nasm-2.12.01-win32.zip

  OGG_SOL_FILE: libogg_static.sln
  OGG_MSBUILD_CMD_X86: /m /p:Configuration=Release;Platform=Win32
  OGG_MSBUILD_CMD_X64: /m /p:Configuration=Release;Platform=x64

  VORBIS_SOL_FILE: vorbis_static.sln
  VORBIS_MSBUILD_CMD_X86: /m /p:Configuration=Release;Platform=Win32 /t:libvorbisfile
  VORBIS_MSBUILD_CMD_X64: /m /p:Configuration=Release;Platform=x64   /t:libvorbisfile

  FLAC_SOL_FILE: libFLAC_static.sln
  FLAC_MSBUILD_CMD_X86: /m /p:Configuration=Release;Platform=x86
  FLAC_MSBUILD_CMD_X64: /m /p:Configuration=Release;Platform=x64

  VORBIS-TOOLS_SOL_FILE: vorbis-tools.sln
  VORBIS-TOOLS_MSBUILD_CMD_X86: /m /p:Configuration=Release;Platform=Win32
  VORBIS-TOOLS_MSBUILD_CMD_X64: /m /p:Configuration=Release;Platform=x64

# clone directory
clone_folder: *REPO_DIR


#---------------------------------#
#  build configuration            #
#---------------------------------#

# scripts to run before build
before_build:
  # git submodules, https does not support `--depth 1` :(
  - cd "%REPO_DIR%"
  - git submodule update --init --remote --recursive

  # install NASM
  - cd \
  - appveyor DownloadFile "%NASM_URL%" -FileName "c:\nasm.zip"
  - 7z x "nasm.zip" > nul
  - move nasm-* NASM
  - set PATH=%PATH%;c:\NASM;
  - nasm -v

  # prepare ogg
  - cd "%REPO_DIR%"
  - if exist "lib\ogg\win32\VS2015" (rd /S /Q "lib\ogg\win32\VS2015")
  - move /Y "src\ogg\VS2015" "lib\ogg\win32"
  - msbuild "lib\ogg\win32\VS2015\%OGG_SOL_FILE%" %OGG_MSBUILD_CMD_X86%
  - msbuild "lib\ogg\win32\VS2015\%OGG_SOL_FILE%" %OGG_MSBUILD_CMD_X64%

  # prepare vorbis
  - cd "%REPO_DIR%"
  - if exist "lib\vorbis\win32\VS2015" (rd /S /Q "lib\vorbis\win32\VS2015")
  - move /Y "src\vorbis\VS2015" "lib\vorbis\win32"
  - msbuild "lib\vorbis\win32\VS2015\%VORBIS_SOL_FILE%" %VORBIS_MSBUILD_CMD_X86%
  - msbuild "lib\vorbis\win32\VS2015\%VORBIS_SOL_FILE%" %VORBIS_MSBUILD_CMD_X64%

    # prepare flac
  - cd "%REPO_DIR%"
  - move /Y "src\flac\libFLAC\*" "lib\flac\src\libFLAC"
  - msbuild "lib\flac\src\libFLAC\%FLAC_SOL_FILE%" %FLAC_MSBUILD_CMD_X86%
  - msbuild "lib\flac\src\libFLAC\%FLAC_SOL_FILE%" %FLAC_MSBUILD_CMD_X64%

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd "%REPO_DIR%"
  - if exist "lib\vorbis-tools\win32\VS2015" (rd /S /Q "lib\vorbis-tools\win32\VS2015")
  - move /Y "src\vorbis-tools\VS2015" "lib\vorbis-tools\win32"
  - msbuild "lib\vorbis-tools\win32\VS2015\%VORBIS-TOOLS_SOL_FILE%" %VORBIS-TOOLS_MSBUILD_CMD_X86%
  - msbuild "lib\vorbis-tools\win32\VS2015\%VORBIS-TOOLS_SOL_FILE%" %VORBIS-TOOLS_MSBUILD_CMD_X64%

# scripts to run before deployment
after_build:
  # prepare for artifacts packaging
  - 'cd "%REPO_DIR%"'
  - 'mkdir "win32" "x64"'
  - 'copy "lib\vorbis-tools\win32\VS2015\Release\*.exe" "win32"'
  - 'copy "lib\vorbis-tools\win32\VS2015\x64\Release\*.exe" "x64"'
  - '7z a -mx9 "vorbis-tools.7z" "Readme.md" "win32" "x64"'  # the artifact must reside at the source repo root
  - 'powershell -Command "& { (Get-FileHash -Algorithm SHA1 "vorbis-tools.7z").hash; }" > "vorbis-tools.7z.sha1"'


#---------------------------------#
#  tests configuration            #
#---------------------------------#

# to disable automatic tests
test: off


#---------------------------------#
#  artifacts configuration        #
#---------------------------------#

artifacts:
  - path: vorbis-tools.7z
    name: exe
  - path: vorbis-tools.7z.sha1
    name: checksum
